marioModel=''
marioModel+='   BBBB.'
marioModel+=' BBBBBBBBBB.'
marioModel+=' CCCDDCD.'
marioModel+='CDCDDDCDDDD.'
marioModel+='CDCCDDDCDDDD.'
marioModel+='CCDDDDCCCC.'
marioModel+='  DDDDDDD.'	

rocketModelV=''
rocketModelV+='   B.'
rocketModelV+='  B B.'
rocketModelV+=' BBBBB.'
rocketModelV+='B BBB B.'
rocketModelV+='   B.'

rocketModel=''
rocketModel+='    BB.'
rocketModel+='      BB.'
rocketModel+='BB  BBBBBB.'
rocketModel+='  BBBBBB  BB.'
rocketModel+='BB  BBBBBB.'
rocketModel+='      BB.'
rocketModel+='    BB.'
