marioModel=''
marioModel+='   BBBB.'
marioModel+=' BBBBBBBBBB.'
marioModel+=' CCCDDCD.'
marioModel+='CDCDDDCDDDD.'
marioModel+='CDCCDDDCDDDD.'
marioModel+='CCDDDDCCCC.'
marioModel+='  DDDDDDD.'	

rocketModelV=''
rocketModelV+='    B.'
rocketModelV+='   B B.'
rocketModelV+='  BBBBB.'
rocketModelV+=' B BBB B.'
rocketModelV+='B B B B B.'
rocketModelV+='    B    .'

rocketModel=''
rocketModel+='    BB.'
rocketModel+='      BB.'
rocketModel+='BB  BBBBBB.'
rocketModel+='  BBBBBB  BB.'
rocketModel+='BB  BBBBBB.'
rocketModel+='      BB.'
rocketModel+='    BB.'

startModel=''
startModel+='BBBBBBB  BBBBBBB       B        BBBBBBB   BBBBBBB.'
startModel+='B           B         BBB       B     B      B.'
startModel+='B           B        B   B      B     B      B.'
startModel+='BBBBBBB     B       BB   BB     BBBBBBB      B.'
startModel+='      B     B      B BBBBB B    B   B        B.'
startModel+='      B     B     B   BBB  BB   B    B       B.'
startModel+='BBBBBBB     B    B     B     B  B     B      B.'

endModel=''
endModel+='BBBBBBB  B     B    B  BBBBBBB    BBBBBB .' 
endModel+='B     B  B     B    B     B      B      B.'
endModel+='B     B  B     B    B     B             B.'
endModel+='BBBBBBB  B     B    B     B           B.'
endModel+='      B  B     B    B     B         B.'
endModel+='      B  B     B    B     B.'
endModel+='      B  BBBBBBB    B     B         B.'
